spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://dumbo.db.elephantsql.com/ghhbpmgd
    username: ghhbpmgd
    password: vWt0G2D-PBw4A5rhtcHIe9b0NP7Agmyv
    driverClassName: org.postgresql.Driver
    database-platform: org.hibernate.dialect.PostgreSQLDialect